### ISSUE TITLE
get_user_apps returns a 500

### ISSUE THREAD

**Issue by admiralobvious** [onelogin/onelogin-python-sdk#11]
`get_user_apps()` returns a 500 because the `login_id`s I get are strings so it breaks on the following [line](https://github.com/onelogin/onelogin-python-sdk/blob/master/src/onelogin/api/models/app.py#L13) because it's trying to cast them to ints.

We monkey-patched the `App` class for now but is it possible to remove the `int()` on your side?

Thank you

**Comment by pitbulk** [comment]
Fixed https://github.com/onelogin/onelogin-python-sdk/commit/36c8a63b9e90a0183d742cd649d0bf2131602eac
1.2.1 version released on gihub

**Comment by admiralobvious** [comment]
Confirmed fixed. Thank you.
