### ISSUE TITLE
Install requires packages strict versions pinned, problem to install python-smal

### ISSUE THREAD

**Issue by nazrulworld** [onelogin/onelogin-python-sdk#13]
Hi 
I am developing [plone package](https://github.com/nazrulworld/plone.app.onelogin)  for onelogin. both saml and onelogin sdk will be used.

I saw in both onelogin-python-sdk and python-saml are using strict version pinning policy of required packages, that actually not good idea unless you badly needed in sense of compatibility with other project 

My Current problem is that [zope's buildout ](https://pypi.python.org/pypi/zc.buildout) can't install both as you see that onelogin-python-sdk requires `defusedxm` version `0.5.0` whereas python-saml requires `defusedxm` version `0.4.1`. The ultimate result is version conflict!

My thinking here, if possible to pin range pattern of  version. for example  `defusedxm < 0.5.0` or `defusedxm=<0.4.1` something like that

**Comment by pitbulk** [comment]
I think python-saml should be defusedxm =>0.4.1.
