### ISSUE TITLE
Fails to install with python 3.7 on macOS

### ISSUE THREAD

**Issue by dat2** [onelogin/onelogin-python-sdk#16]
`lxml==3.8.0` fails to install with a C compiler error on python 3.7, released June 29 2018.

`lxml-4.1.1` is the minimum version that successfully installs on python 3.7, but I haven't tried using that version with this.

OS: macOS High Sierra, 10.13.4

**Comment by pitbulk** [comment]
I see that 4.0.0 fixes 

```
Compilation under Py3.7-pre failed due to a modified function signature.
```

Reference: https://lxml.de/4.2/changes-4.2.3.html

**Comment by pitbulk** [comment]
I updated the dependencies https://github.com/onelogin/onelogin-python-sdk/commit/409e7af3a8c82713ae46da25a307ea174796a9f0

**Comment by dat2** [comment]
Thanks @pitbulk for resolving this issue so quickly!
