### ISSUE TITLE
Upgrade lxml to 4.2.3

### ISSUE THREAD

**Issue by admiralobvious** [onelogin/onelogin-python-sdk#17]
I see you require lxml to be version 4.2.2 in 1.4.0, that version has a major issue that breaks Pillow/PIL and others. See [here](https://github.com/python-pillow/Pillow/issues/3208). Can you change the dependency to be 4.2.3?

Upgrading onelogin to 1.4.0 upgraded our lxml version which broke some Pillow code we're using, which is why I am asking.

Thanks

**Comment by pitbulk** [comment]
Ok

**Comment by pitbulk** [comment]
Released [1.4.1](https://github.com/onelogin/onelogin-python-sdk/releases/tag/1.4.1)
