### ISSUE TITLE
No module named api.client

### ISSUE THREAD

**Issue by philross88** [onelogin/onelogin-python-sdk#21]
I am trying to use the python SDK for some automation, however, when I try to execute the sample code to get the user's, it's failing with the below error message.

```
python onelogin.py 
Traceback (most recent call last):
  File "onelogin.py", line 1, in <module>
    from onelogin.api.client import OneLoginClient
  File "/root/onelogin.py", line 1, in <module>
    from onelogin.api.client import OneLoginClient
ImportError: No module named api.client
```

Following is the code that I am trying to execute:

```
from onelogin.api.client import OneLoginClient

client_id = "XXXX"
client_secret = "XXX..."
client = OneLoginClient(
    client_id, 
    client_secret
    )

# Now you can make requests
client.get_users()

```

**Comment by pitbulk** [comment]
"No module named api.client"

It seems that the python script was not able to load the sdk.

**Comment by philross88** [comment]
/onelogin/bin$ ./python 
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from onelogin.api.client import OneLoginClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umz/onelogin/local/lib/python2.7/site-packages/onelogin/api/client.py", line 13, in <module>
    from dateutil import tz
  File "/home/umz/onelogin/local/lib/python2.7/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/home/umz/onelogin/local/lib/python2.7/site-packages/dateutil/tz/tz.py", line 17, in <module>
    import six
ImportError: No module named six

**Comment by pitbulk** [comment]
ImportError: No module named six

You may install six
https://pypi.org/project/six/

**Comment by philross88** [comment]
Yeah, I have fixed that error. Can you please post the sample code to iterate through each user detail?
I want to see when a particular user has updated the password.
