### ISSUE TITLE
Update requests version in setup.py

### ISSUE THREAD

**Issue by pattyr** [onelogin/onelogin-python-sdk#25]
Thank you for the quick response and turn around for this issue https://github.com/onelogin/onelogin-python-sdk/issues/24, I really appreciate it! :)

I saw pypi was updated with `onelogin 1.5.2`, but am getting the same error as https://github.com/onelogin/onelogin-python-sdk/issues/24.

Then noticed `setup.py` still has `requests==2.19.1` on the master branch.
https://github.com/onelogin/onelogin-python-sdk/blob/master/setup.py#L41

**Comment by pitbulk** [comment]
Oh, sorry for that.
https://github.com/onelogin/onelogin-python-sdk/releases/tag/1.5.3

**Comment by pattyr** [comment]
It worked perfectly! Thank you again!
