### ISSUE TITLE
get_event_types not returning 'description' field

### ISSUE THREAD

**Issue by bryanpearson** [onelogin/onelogin-python-sdk#30]
When calling `client.get_event_types()`, only `id` and `name` fields are returned in the type object. The API documentation shows a `description` field as well, as seen here: https://developers.onelogin.com/api-docs/1/events/event-types

Anything I can do to get the description field returned with the list of types? Thanks.

**Comment by pitbulk** [comment]
Thanks for reporting that, we will update the SDK to take the description field.
