### ISSUE TITLE
Several attributes missing from Event object model

### ISSUE THREAD

**Issue by dalewl** [onelogin/onelogin-python-sdk#31]
https://github.com/onelogin/onelogin-python-sdk/blob/bbb7c76870b5441f5b44f9950cad70f946d7c45b/src/onelogin/api/models/event.py#L40

With the addition of risk scoring to the Events API, yesterday, several attributes need to be added here.  Here is an example of the fields, from a record just retrieved from the Events API:
            "risk_score": 1,
            "risk_reasons": "Chrome on X11 is used infrequently (100%)",
            "risk_cookie_id": "708c8a84-1dfa-4922-8258-68f89ca36267",
            "browser_fingerprint": "93dd4e08606861dbdbbc52fb5d1e7ed7"

Also, in looking at what was returned, I noticed that these additional attributes were missing as well, that seem unrelated to the new risk attributes:
            "role_name": null,
            "proxy_ip": null,

**Comment by pitbulk** [comment]
'role_name' was already [there](https://github.com/onelogin/onelogin-python-sdk/blob/master/src/onelogin/api/models/event.py#L23)

I added rest of fields
