### ISSUE TITLE
Strict Requirements Versioning Policy

### ISSUE THREAD

**Issue by jeffries** [onelogin/onelogin-python-sdk#32]
Hi there, I'm attempting to install the `onelogin-python-sdk` package, but am running into some problems with requirements conflicting between this and other packages I am installing. I notice that the `requirements.txt` for this package employs a strict versioning policy for all requirements listed. I wanted to gain some insight into this decision (is there a particular piece of behavior in the specified versions that is required by the package?), and inquire as to whether it would be possible to loosen the requirement versioning policy in order to ease installation of this package alongside other packages. Thanks!

**Comment by pitbulk** [comment]
I think that versioning could be relaxed. I will take care of it on next release.

**Comment by mick88** [comment]
Definitely needs to be more relaxed. No library should need a specific version of another package. If two libraries do this, they will be impossible to install at the same time.
