### ISSUE TITLE
Depending On defusedxml Version 0.5.0 Causes Conflicts

### ISSUE THREAD

**Issue by jannero** [onelogin/onelogin-python-sdk#37]
defusedxml 0.6.0 (released on April 17th 2019) deprecated an unused html argument for DefusedXMLParser aliased by XMLParse (see https://pypi.org/project/defusedxml/#changelog).

As onelogin currently requires version 0.5.0 of defusedxml there are version conflicts from other libraries that are requiring a newer version of defusedxml.

onelogin does not use the changed class at all and there already is a commit 680d7718eb27b7b87f3c1b7fe09e4d933fa2646d that relaxes the version requirements so to fix this issue, the only thing to would be to release a new version from master branch.

**Comment by pitbulk** [comment]
The [PR](https://github.com/onelogin/onelogin-python-sdk/pull/36) that relaxes the dependencies was already merged, but no official release was released, so you are experiencing issues.

**Comment by jannero** [comment]
Yes, that is what I was referring to: you should release new version that includes the mentioned commit.

I habe workwd around the issue by installing onelogin from github instead of pypi

**Comment by pitbulk** [comment]
1.8.2 version released and available on pypi.
