### ISSUE TITLE
Retrieving attributes from ws-federation response

### ISSUE THREAD

**Issue by vinothkumar1097** [onelogin/onelogin-python-sdk#38]
Hi Team,

Im not sure is my issue related to this library. 
Actually i have implemented sso in my flask app using my company web.config file which is a ws-federation. Login and re-routing is working fine  now.

But the issue, i couldn’t get the saml response from it. I could see that all the user attributes are present in saml response. Im not sure is there any python library that i can use to get those attributes.

Thanks,
Vinod

**Comment by pitbulk** [comment]
You can use:
- https://github.com/onelogin/python-saml
- https://github.com/onelogin/python3-saml

**Comment by vinothkumar1097** [comment]
> You can use:
> 
> * https://github.com/onelogin/python-saml
> * https://github.com/onelogin/python3-saml

**Comment by vinothkumar1097** [comment]
Hi Pitbulk,

I checked those libraries, but im bit confused how the library will resolve my issue.
As i said earlier, I haven’t used python3-saml in my flask app to intiate sso instead i used my company’s web.config(which is a ws-federation) file. Through this, when a user enters this link they first redirected to our idp page and after successfull login they redirected to my flask app.

But the issue is, from acs response, i can see those user attributes which i couldn’t get through python. If i use python3-saml here,
I need to remove WS federation which is against our company policy.

So is there any way, that i can use python3-saml library for only retrieving the user attributes rather than full saml implementation?

**Comment by pitbulk** [comment]
Yes, take a look at [response.py](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py)

**Comment by vinothkumar1097** [comment]
Hi Pitbulk,

I've done the same what you instructed. But after my page successfully authenticated via my web.config(ws federation), the page is throwing error.

**Error message**
 auth.process_response(request_id=None)
  File "D:\A697643\PythonApp\venv\lib\site-packages\onelogin\saml2\auth.py", line 135, in process_response  OneLogin_Saml2_Error.SAML_RESPONSE_NOT_FOUND
onelogin.saml2.errors.OneLogin_Saml2_Error: SAML Response not found, Only supported HTTP_POST Binding

![ws federation response](https://user-images.githubusercontent.com/35162372/74456073-49ef9180-4eac-11ea-8701-d2f97670bfe9.png)

###  ws federation authentication is successfull at this point and response can be seen as shown above. Once it enter into the route url, the page is not getting loaded and showing above error.

**Complete code**
def prepare_from_request(request):
    url_data = urlparse(request.url)
    return {
        'https': 'on' if request.scheme == 'https' else 'off',
        'http_host': request.host,
        'server_port': url_data.port,
        'script_name': request.path,
        'get_data': request.args.copy(),
        'post_data': request.form.copy(),
        'query_string': request.query_string
    }

def init_saml_auth(req):
    auth = OneLogin_Saml2_Auth(req, custom_base_path=app.config['SAML_PATH'])
    return auth

@app.route('/', methods=['GET','POST'])
def home():
    req = prepare_from_request(request)
    auth = init_saml_auth(req)
    request_id = None
    auth.process_response(request_id=None)
    errors = auth.get_errors()
    if len(errors) == 0:
        return auth.get_attributes().items()
    elif auth.get_settings().is_debug_active():
        error_reason = auth.get_last_error_reason()
        return 'Error {0}'.format(error_reason)

Am i doing anything wrong Pitbulk. pls assist me.
