### ISSUE TITLE
SAML API v1 should be updated to v2

### ISSUE THREAD

**Issue by jutley** [onelogin/onelogin-python-sdk#41]
This library is built off of the OneLogin v1 API. In the [documentation for the SAML API v1](
https://developers.onelogin.com/api-docs/1/saml-assertions/generate-saml-assertion), there is a warning that states the following:
> This version is deprecated and will be removed in February 2021.

In the constants, we can see that we are using v1 for the SAML APIs
https://github.com/onelogin/onelogin-python-sdk/blob/65290eb20cc9a7fc0fe5556a9c4b9e6cc2f1a9df/src/onelogin/api/util/constants.py#L70-L71

This should be updated soon to give time for clients to be updated.

**Comment by pitbulk** [comment]
@jutley It took time but at https://github.com/onelogin/onelogin-python-sdk/tree/2.0.0 you will find a new version of the SDK compatible with /1 and /2

**Comment by marcusvoss** [comment]
@jutley acan you think of a release date for this branch?
Alternatively would you (or someone else) can give me a hint, how to do "pip3 install <branch 2.0.0>", so that I could use it already?

Thanks in advance
