### ISSUE TITLE
Issues related to get_events

### ISSUE THREAD

**Issue by akshay-pange-exa** [onelogin/onelogin-python-sdk#56]
When calling `def get_events(self, query_parameters=None, max_results=None`) facing following issues:
1. In query_parameters for non existing value it returns None(instead of empty list) and if you check for errors it returns
```
 client.error : 500 
 error_description :  local variable 'data' referenced before assignment
```
e.g   `query_parameters = {"user_id": 12345} Here 12345=non existing value(user_id not exist)`

2. With query_parameters id (which is supported filter parameter for events) it returns None and 
```
client.error  : 400
client.error_description  : Integer value must be <= 2147483647
```
3. Also the error type for above case 1 is `int` and for other cases `str`.
    case 1 it return `500 `in `integer` while in case 2 it return `400 `in `string`.

**Comment by pitbulk** [comment]
@akshay-pange-exa ar you using the V1 or V2 branch?

**Comment by pitbulk** [comment]
I fixed the bug discovered on scenario 1)

None is an expected result when an error is raised on the SDK, on 2) it seems you queried for an integer like 999999999999999
"Integer value must be <= 2147483647" is a validation executed on the server side and the SDK manages it.

In [V2](https://github.com/onelogin/onelogin-python-sdk/tree/v2) you can execute:
```
events = client.get_events({'user_id': 59304500})
or
events = client.get_events({'user_id': '59304500'})
```
and both gonna work
