### ISSUE TITLE
`app_id` shouldn't be mandatory for `list_users`

### ISSUE THREAD

**Issue by aitorCerecetoGlovoApp** [onelogin/onelogin-python-sdk#70]
Currently `app_id` is mandatory for `list_users` method. That's not true at all because you can query users without need to filter by app if the users don't have any app assigned.

**Comment by aitorCerecetoGlovoApp** [comment]
Would be good if you can host the yaml file in order to help to contribute the development of this SDK in case we need to use it and it's bugged.

**Comment by matteosilv** [comment]
@aitorCerecetoGlovoApp did you end up with a work-around for it? I'm still using 2.0.4 sdk...

**Comment by Jmfwolf** [comment]
I have created a beta for python. I have removed the erroneous app_id requirement.
https://github.com/onelogin/onelogin-python-sdk/releases/tag/3.1.1

We have been discussing the best location for the spec itself. It is planned to release in the future.

**Comment by aitorCerecetoGlovoApp** [comment]
thanks @Jmfwolf ! it would be possible to be hosted as pip package?

@matteosilv yeah me too. I'm using 2.0.4 sdk because seems more understandable and easier to use currently.

**Comment by Jmfwolf** [comment]
I am glad that it was fixed. Yeah, I am working on the workflow to automate the release to pypi.
