### ISSUE TITLE
app_id should not be mandatory for list_roles

### ISSUE THREAD

**Issue by catrielg** [onelogin/onelogin-python-sdk#81]
Similar issue to https://github.com/onelogin/onelogin-python-sdk/issues/70

The list_roles operation required an app_id but this is not the case with the REST API as you can list all roles without specifying an app.

**Comment by catrielg** [comment]
I am using 2.0.4 on purpose due to the fact that since version 3 it's not been comfortable using the library at all and the auto-generated documentation is not very helpful

**Comment by Jmfwolf** [comment]
I understand. I am working changes to the templates for the READMEs that are generated. I will make an issue for it so I can prioritize that for this repo.

**Comment by catrielg** [comment]
Awesome, thanks
