### ISSUE TITLE
Issue with 'list_privileges' function

### ISSUE THREAD

**Issue by Tommy-Lightning** [onelogin/onelogin-python-sdk#85]
In lines 1226-1252 of [(https://github.com/onelogin/onelogin-python-sdk/blob/master/onelogin/api/privileges_api.py)]

kwargs are asked for by the function but do not need to be given - looks for a list but the output should be a list.

**Comment by Jmfwolf** [comment]
Thank you for bringing this to my attention. I will keep you updated as I correct these issues

**Comment by Jmfwolf** [comment]
The issue should be resolved. So long as you have sufficient access to the privileges endpoint

**Comment by Jmfwolf** [comment]
Please try the pre-release https://github.com/onelogin/onelogin-python-sdk/releases/tag/3.1.6
