### ISSUE TITLE
Action Object misses support for some action types

### ISSUE THREAD

**Issue by bitte-ein-bit** [onelogin/onelogin-python-sdk#90]
According to the (API documentation)[https://developers.onelogin.com/api-docs/2/app-rules/create-rule] more actions are supported:

> An array of actions that will be applied to the users that are matched by the conditions.
> * `action` - The action to apply. See [List Actions](https://developers.onelogin.com/api-docs/2/app-rules/list-conditions) for possible values.
> * `value` - An array of strings. Only applicable to provisioned and set_* actions. Items in the array will be a plain text string or valid value for the selected action. See [List Action Values](https://developers.onelogin.com/api-docs/2/app-rules/list-action-values) for possible values. In most cases, only a single item will be accepted in the array.
> * `expression` - A regular expression to extract a value. Applies to provisionable, multi-selects, and string actions.
> * `scriplet` - A hash containing scriptlet code that returns a value. Scriptlets can not be modified, and the same hash should not be applied to other applications.
> * `macro` - A template to construct a value. Applies to default, string, and list actions

Only `action` and `value` is currently supported.

@Jmfwolf I tried looking into how to update the code to provide a pull request. I have no experience with OpenApi Generator, and I couldn't figure it out. Maybe adding some lines to the repo on how to update/contribute is worth it?

**Comment by Jmfwolf** [comment]
Please try the pre-release https://github.com/onelogin/onelogin-python-sdk/releases/tag/3.1.6

**Comment by Jmfwolf** [comment]
It has been merged and is considered closed
